[project]
name = "fastapi-sqlx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy[asyncio]>=2.0.44",
]

[dependency-groups]
dev = [
    "pydantic>=2.12.5",
    "ruff>=0.14.8",
]
